In [1]:
# Import all the things

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from ipywidgets import interactive
from IPython.display import display
import ipywidgets as widgets
from ipywidgets import interact, widgets


# %matplotlib inline

In [2]:
# Read in data

workshops  = pd.read_csv('workshops.csv')

## Preview the whole dataframe

In [3]:
# Preview data

workshops

,slug,tag_name,yr,attendance,fullname,administrator_id
0,2011-11-07-toronto,SWC,2011,22.0,University of Toronto,297.0
1,2012-01-18-stsci,SWC,2012,14.0,Space Telescope Science Institute,173.0
2,2012-02-20-itcp,SWC,2012,50.0,International Centre for Theoretical Physics,306.0
3,2012-02-23-toronto,SWC,2012,28.0,University of Toronto,297.0
4,2012-03-07-indiana,SWC,2012,39.0,Indiana University,173.0
5,2012-03-26-mbari,SWC,2012,38.0,Monterey Bay Aquarium Research Institute,173.0
6,2012-03-28-nersc,SWC,2012,35.0,NERSC,173.0
7,2012-04-02-chicago,SWC,2012,35.0,University of Chicago,173.0
8,2012-04-14-utahstate,SWC,2012,32.0,Utah State University,173.0
9,2012-04-30-ucl,SWC,2012,44.0,University College London,278.0
10,2012-05-07-michiganstate,SWC,2012,55.0,Michigan State University,173.0
11,2012-05-14-newcastle,SWC,2012,41.0,University of Newcastle,278.0
12,2012-05-16-alberta,SWC,2012,38.0,University of Alberta,297.0
13,2012-05-22-ubc,SWC,2012,39.0,University of British Columbia,297.0
14,2012-06-18-jhu,SWC,2012,20.0,Johns Hopkins University,173.0
15,2012-06-28-inria,SWC,2012,28.0,INRIA (Paris),306.0
16,2012-07-09-mit,SWC,2012,36.0,Massachusetts Institute of Technology,173.0
17,2012-07-10-ral,SWC,2012,24.0,Science & Technology Facilities Council,278.0
18,2012-07-12-waterloo,SWC,2012,40.0,University of Waterloo,297.0
19,2012-07-16-halifax,SWC,2012,40.0,Saint Mary's University,297.0
20,2012-07-19-utsc,SWC,2012,39.0,University of Toronto (Scarborough),297.0
21,2012-08-26-ttt-online,"TTT,online",2012,20.0,Software Carpentry,173.0
22,2012-09-13-dafx,SWC,2012,33.0,DAFX Conference,278.0
23,2012-09-17-oslo,SWC,2012,34.0,University of Oslo,306.0
24,2012-09-28-columbia,SWC,2012,39.0,Columbia University,173.0
25,2012-10-08-purdue,SWC,2012,42.0,Purdue University,173.0
26,2012-10-11-ttt-online,"TTT,online",2012,25.0,Software Carpentry,173.0
27,2012-10-17-lbl,SWC,2012,40.0,Lawrence Berkeley National Laboratory,173.0
28,2012-10-18-ubc,SWC,2012,62.0,University of British Columbia,297.0
29,2012-10-20-ucb,SWC,2012,29.0,University of California Berkeley,173.0
...,...,...,...,...,...,...
1353,2017-11-30-MBARI,SWC,2017,44.0,Monterey Bay Aquarium Research Institute,343.0
1354,2017-11-30-NWU-IT,SWC,2017,16.0,North-West University,343.0
1355,2017-11-30-minnesota,SWC,2017,18.0,University of Minnesota,173.0
1356,2017-11-30-queensu,SWC,2017,25.0,Queen's University,297.0
1357,2017-12-01-gwu-Python,SWC,2017,15.0,George Washington University,173.0
1358,2017-12-02-UCSF-Python,SWC,2017,24.0,University of California San Francisco,173.0
1359,2017-12-02-UCSF-R,SWC,2017,34.0,University of California San Francisco,173.0
1360,2017-12-02-mun,SWC,2017,33.0,Memorial University,343.0
1361,2017-12-04-standrews,SWC,2017,17.0,University of St. Andrews,278.0
1362,2017-12-04-ttt,"TTT,online",2017,8.0,Software Carpentry,173.0
1363,2017-12-05-rutgers,DC,2017,34.0,Rutgers University,302.0
1364,2017-12-05-ttt-southampton,TTT,2017,18.0,Software Carpentry,173.0
1365,2017-12-07-Monsanto,SWC,2017,NaN,Monsanto,343.0
1366,2017-12-11-Imperial,SWC,2017,26.0,Imperial College London,343.0
1367,2017-12-12-MQU-R,SWC,2017,34.0,Macquarie University,121.0
1368,2017-12-12-acadia,SWC,2017,23.0,Acadia University,343.0
1369,2017-12-12-ttt-online,"TTT,online",2017,16.0,Software Carpentry,173.0
1370,2017-12-13-amsterdam,DC,2017,11.0,University of Amsterdam,302.0
1371,2017-12-14-MAN-SS-PILOT01,DC,2017,NaN,University of Manchester,343.0
1372,2017-12-14-UCL_software_carpentry,SWC,2017,NaN,University College London,343.0
1373,2017-12-14-mcmaster,DC,2017,27.0,McMaster University,297.0
1374,2017-12-14-ttt-uiuc,TTT,2017,10.0,Software Carpentry,173.0
1375,2017-12-14-ucr,LC,2017,9.0,"University of California, Riverside",343.0
1376,2017-12-18-PNNL,SWC,2017,NaN,Pacific Northwest National Lab,343.0
1377,2017-12-18-grand-valley,DC,2017,19.0,Grand Valley State University,302.0
1378,2017-12-18-knoxville,SWC,2017,31.0,University of Tennessee Knoxville,343.0
1379,2017-12-18-osu,SWC,2017,NaN,Oklahoma State University,343.0
1380,2017-12-18-umich,SWC,2017,15.0,University of Michigan,343.0
1381,2017-12-20-normandale,SWC,2017,19.0,Winona State University,173.0
1382,datacarpentry_2015-11-23_VLSCI,DC,2015,18.0,VLSCI,343.0

In [4]:
def workshops_by_year(data, year): 
    """Takes a dataframe and a year, returns dataframe filtered by year"""
    df = pd.read_csv(data)
    df = df[df['yr'] == year]
    return df

## Select a year to see a dataframe of all workshops (across Carpentries) that year

In [5]:
# The interact function takes as arguments the function and that function's arguments separately
interact(workshops_by_year, data = 'workshops.csv', year = range(2011, 2018))

A Jupyter Widget

In [6]:
def workshops_by_carpentry(data, carpentry): 
    """Takes a dataframe and a carpentry, returns dataframe filtered by that carpentry"""
    df = pd.read_csv(data)
    df = df[df['tag_name'].str.contains(carpentry)]
    return df

## Select a Carpentry to see a dataframe of all workshops for that Carpentry (across all years)

In [7]:
interact(workshops_by_carpentry, data = 'workshops.csv', carpentry = ['SWC', 'DC', 'LC'])

A Jupyter Widget

In [8]:
def attendance_by_carpentry_and_year(data, carpentry): 
    """Takes a dataframe and a carpentry, returns attendance total by year for that carpentry as pandas series and bar plot"""
    df = pd.read_csv(data)
    df = df[df['tag_name'].str.contains(carpentry)]
    attendance_by_year = df.groupby('yr')['attendance'].sum()
   
    attendance_list = attendance_by_year.tolist()
    
    offset = max(attendance_list) * .025
    ax = attendance_by_year.plot(x = 'yr', y = 'attendance', kind = 'bar')
    for i in range(len(attendance_list)):
        ax.text(i, attendance_list[i] + offset, str(int(attendance_list[i])))
    plt.show()
    
    return attendance_by_year

## Select a Carpentry to see a bar chart of attendance by year for that Carpentry

This does not account for workshops missing attendance

In [9]:
interact(attendance_by_carpentry_and_year, data = 'workshops.csv', carpentry = ['SWC', 'DC', 'LC'])

A Jupyter Widget

In [10]:
def workshops_by_carpentry_and_year(data, carpentry="All", yr="All", stacked = True, agg="workshop count"): 
    """Takes a dataframe and a carpentry, returns dataframe filtered by that carpentry"""
    df = pd.read_csv(data)
    df.loc[df.administrator_id != 343, 'administrator_id'] = 'centrally'
    df.loc[df.administrator_id == 343, 'administrator_id'] = 'self'
    
    df.loc[df["tag_name"].str.contains("SWC"), 'tag_name'] = "SWC"
    df.loc[df["tag_name"].str.contains("DC"), 'tag_name'] = "DC"
    df.loc[df["tag_name"].str.contains("LC"), 'tag_name'] = "LC"
    df.loc[df["tag_name"].str.contains("TTT"), 'tag_name'] = "TTT"

    if carpentry != "All":
        df = df[df['tag_name'].str.contains(carpentry)]
    if yr != "All":
        df = df[df['yr'] == yr]
    
    if agg == "workshop count":
        attendance_by_year = df.groupby(['yr', 'tag_name', 'administrator_id'])['slug'].count()
    elif agg == "attendance sum":
        attendance_by_year = df.groupby(['yr', 'tag_name', 'administrator_id'])['attendance'].sum()

    attendance_by_year = attendance_by_year.to_frame()
    attendance_by_year.unstack().plot(kind='bar', stacked=stacked)

    return attendance_by_year

## Seelct a Carpentry and year to see a bar chart of workshop count OR attendance total for that Carpentry/year and that bar chart's source dataframe by self organized and centrally organized workshops.  Select "stacked" to toggle stacked view or side by side view.

This does not account for workshops missing attendance.  See here on how to fill na with means: 
https://chrisalbon.com/python/data_wrangling/pandas_missing_data/

Need to figure out how to make the legends and labels more human readable.

In [11]:
interact(workshops_by_carpentry_and_year, data = 'workshops.csv', stacked = [True, False], carpentry = ['All', 'SWC', 'DC', 'LC', 'TTT'], yr = ["All"] + list(range(2011, 2019)), agg=["attendance sum", "workshop count"])

A Jupyter Widget